#!/usr/bin/env python3
"""Generate the DSP kernels for tgk_ops.py's ops -- plain tinygrad Tensor code and the hand custom_kernels -- check
each exact against numpy under qemu (DEV=DSP MOCKDSP=1), and write their C into one header for the on-phone harness.

  PYTHONPATH=<onnxsim/tinygrad hvx-codegen checkout> CC=clang-19 python gen_kernels.py --size real --out kernels.h

Also writes <out_dir>/<op>_in*.bin / <op>_ref.bin (the inputs and numpy reference) for tgk_client."""
import argparse, os, re, sys
os.environ.setdefault("DEV", "DSP"); os.environ.setdefault("MOCKDSP", "1")
import numpy as np
from tinygrad.renderer.cstyle import ClangRenderer
import tgk_ops

captured: list[str] = []
_orig = ClangRenderer.render
def _capture(self, uops):
  src = _orig(self, uops); captured.append(src); return src
ClangRenderer.render = _capture

def kernel_c(src:str, new_name:str) -> tuple[list[str], str]:
  body = src.split("/* DSP boilerplate */")[0]
  typedefs = [l for l in body.splitlines() if l.startswith("typedef ")]
  code = "\n".join(l for l in body.splitlines() if not l.startswith("typedef ")).strip()
  name = re.search(r"void\s+(\w+)\(", code).group(1)
  return typedefs, re.sub(rf"\b{name}\b", new_name, code)

def build(op:str, variant:str, ins:list[np.ndarray], ref:np.ndarray) -> tuple[list[str], str, bool]:
  captured.clear()
  out = (tgk_ops.plain if variant == "gen" else tgk_ops.hand)(op, ins).realize().numpy().reshape(ref.shape)
  exact = bool(np.array_equal(out, ref))
  assert len(captured) == 1, f"{op}/{variant}: expected one compiled kernel, got {len(captured)}"
  td, code = kernel_c(captured[0], f"{variant}_{op}")
  return td, code, exact

if __name__ == "__main__":
  p = argparse.ArgumentParser()
  p.add_argument("--size", choices=["small", "real"], default="real")
  p.add_argument("--out", default="kernels.h")
  p.add_argument("--ops", default="add,bias_add,relu,maxpool,requant")
  a = p.parse_args()
  out_dir = os.path.dirname(os.path.abspath(a.out))
  typedefs: list[str] = []
  funcs: list[str] = []
  for op in a.ops.split(","):
    ins = tgk_ops.inputs(op, a.size)
    ref = tgk_ops.reference(op, ins)
    for i, x in enumerate(ins): x.tofile(os.path.join(out_dir, f"{op}_in{i}.bin"))
    ref.tofile(os.path.join(out_dir, f"{op}_ref.bin"))
    for variant in ("gen", "hand"):
      td, code, exact = build(op, variant, ins, ref)
      print(f"{op:8s} {variant:4s} shape={ref.shape} qemu exact={exact}")
      if not exact: sys.exit(f"{op}/{variant} is not exact under qemu")
      typedefs += [t for t in td if t not in typedefs]
      funcs.append(f"/* {op}, {'plain tinygrad Tensor code' if variant == 'gen' else 'hand custom_kernel'} */\n{code}")
  with open(a.out, "w") as f:
    f.write("/* generated by gen_kernels.py -- do not edit */\n" + "\n".join(typedefs) + "\n\n" + "\n\n".join(funcs) + "\n")
  print(f"wrote {a.out}")
