"""MCC decoder blocks as plain tinygrad Tensor code, generated by the onnxsim/tinygrad fork's DSP backend
(branch hvx-hmx: HVX codegen, qfloat, the HMX TensorCore), compared with the hand-written ../mcc_block.h.

  HMX=1 DEV=DSP MOCKDSP=1 TC=1 HVX_ARCH=v69 CC=clang-19 PYTHONPATH=<tinygrad hvx-hmx> \
    python mcc_tg.py check --data <ref.py export dir> --q 64 [--blocks 1]

`check` runs the blocks through tinygrad under MOCKDSP (qemu; HMX kernels as the TensorCore's scalar
reference) on the ref.py export's x0 and compares with its float64 block references; it also records
every kernel call (source + argument buffers) for `emit`, which writes a hexagon-sim / skel program
around the same kernels rebuilt for real HMX (see capture.py). --no-run records without executing:
qemu-hexagon can't decode the qfloat code the fork now emits (decode_packet assertion), so these kernels
are checked by replaying them on hexagon-sim (emit.py) instead.

The math is model.py's QueryDecoder block, written for the TensorCores: the 197 seen K / V padded to
224 (a multiple of 32) with the padded scores masked to -inf, matmuls in fp16 (fp16 accumulation, as
the HMX tile op), LayerNorm statistics / softmax / GELU (tanh form, as the hand kernel) in fp32.
"""

import argparse
import sys
from pathlib import Path

import numpy as np

HERE = Path(__file__).resolve().parent
sys.path.insert(0, str(HERE.parent))
sys.path.insert(0, str(HERE.parent.parent / "vision_models" / "mcc"))

D, HEADS, HD, SEEN, SEEN_PAD = 512, 16, 32, 197, 224


def block_weights(blk, k, v):
    """numpy fp16 weights of one torch block + its seen K / V (16, 197, 32), padded for the TensorCores"""
    a = blk.attn
    f16 = lambda t: t.detach().numpy().astype(np.float16)  # noqa: E731
    kp = np.zeros((HEADS, HD, SEEN_PAD), np.float32)
    kp[:, :, :SEEN] = k.transpose(0, 2, 1) * a.scale
    vp = np.zeros((HEADS, SEEN_PAD, HD), np.float32)
    vp[:, :SEEN] = v
    mask = np.zeros(SEEN_PAD, np.float32)
    mask[SEEN:] = -1e4  # effectively -inf after the softmax, without infinities in qfloat code
    return {
        "ln1": (f16(blk.norm1.weight), f16(blk.norm1.bias)),
        "wqkv": f16(a.qkv.weight).T.copy(),
        "bqkv": f16(a.qkv.bias),
        "wproj": f16(a.proj.weight).T.copy(),
        "bproj": f16(a.proj.bias),
        "ln2": (f16(blk.norm2.weight), f16(blk.norm2.bias)),
        "w1": f16(blk.mlp.fc1.weight).T.copy(),
        "b1": f16(blk.mlp.fc1.bias),
        "w2": f16(blk.mlp.fc2.weight).T.copy(),
        "b2": f16(blk.mlp.fc2.bias),
        "kt": kp.astype(np.float16),  # K^T * scale, (16, 32, 224)
        "vp": vp.astype(np.float16),  # (16, 224, 32)
        "mask": mask,
    }


def tg_block(x, w):
    """one decoder block, tinygrad Tensors (x: (Q, 512) half)"""
    from tinygrad import Tensor, dtypes

    T = lambda a: Tensor(a)  # noqa: E731
    q_n = x.shape[0]

    def ln(t, gb):
        return (t.float().layernorm(eps=1e-6) * T(gb[0]).float() + T(gb[1]).float()).cast(dtypes.half).contiguous()

    # every matmul's A operand is materialized in fp16 (.contiguous()): fused into the matmul's loads (a cast,
    # LayerNorm, GELU), the HMX rewrite can't see plain row loads and falls back to the generic tile op

    qkv = ln(x, w["ln1"]).matmul(T(w["wqkv"]), dtype=dtypes.half) + T(w["bqkv"])
    q, k, v = (qkv[:, i * D : (i + 1) * D].reshape(q_n, HEADS, HD).permute(1, 0, 2) for i in range(3))  # (16, Q, 32)
    # S = q K^T on its own (fused with the concatenate below it is a scalar kernel: 86% of the block): q
    # materialized per head, S materialized before the mask / concatenate
    s = q.contiguous().matmul(T(w["kt"]), dtype=dtypes.half).contiguous().float() + T(w["mask"])  # (16, Q, 224)
    ss = (q.float() * k.float()).sum(-1, keepdim=True) * (HD**-0.5)  # (16, Q, 1)
    # softmax over [S (224 wide), s_self] with the self term kept apart (as the hand kernel): 224 = 7 x 32 vectorizes, a
    # 225-wide concatenated row does not
    m = s.max(-1, keepdim=True).maximum(ss)
    e, es = (s - m).exp(), (ss - m).exp()
    inv = 1.0 / (e.sum(-1, keepdim=True) + es)
    o = (e * inv).cast(dtypes.half).contiguous().matmul(T(w["vp"]), dtype=dtypes.half).float() + (es * inv) * v.float()
    o = o.cast(dtypes.half).permute(1, 0, 2).reshape(q_n, D).contiguous()
    x = x + o.matmul(T(w["wproj"]), dtype=dtypes.half) + T(w["bproj"])
    # fc1's output is materialized before GELU: fused into the matmul's epilogue, tinygrad unrolls GELU over
    # every output tile element by element (1.5 MB of C for fc1, 10+ minutes of clang); tanh form, as the
    # hand kernel (tinygrad's erf is a rational approximation with scalar divisions)
    h = (ln(x, w["ln2"]).matmul(T(w["w1"]), dtype=dtypes.half) + T(w["b1"])).contiguous()
    g = h.float().gelu(approximate="tanh").cast(dtypes.half).contiguous()
    return x + g.matmul(T(w["w2"]), dtype=dtypes.half) + T(w["b2"])


def block_weights_t(blk, k, v):
    """block_weights for the feature-major block: torch's own (out, in) weights are the HMX A operands as they are"""
    a = blk.attn
    f16 = lambda t: t.detach().numpy().astype(np.float16)  # noqa: E731
    km = np.zeros((HEADS, SEEN_PAD, HD), np.float32)
    km[:, :SEEN] = k * a.scale
    vt = np.zeros((HEADS, HD, SEEN_PAD), np.float32)
    vt[:, :, :SEEN] = v.transpose(0, 2, 1)
    mask = np.zeros((SEEN_PAD, 1), np.float32)
    mask[SEEN:] = -1e4
    col = lambda t: f16(t).reshape(-1, 1)  # noqa: E731
    return {
        "ln1": (col(blk.norm1.weight), col(blk.norm1.bias)),
        "wqkv": f16(a.qkv.weight), "bqkv": col(a.qkv.bias),
        "wproj": f16(a.proj.weight), "bproj": col(a.proj.bias),
        "ln2": (col(blk.norm2.weight), col(blk.norm2.bias)),
        "w1": f16(blk.mlp.fc1.weight), "b1": col(blk.mlp.fc1.bias),
        "w2": f16(blk.mlp.fc2.weight), "b2": col(blk.mlp.fc2.bias),
        "km": km.astype(np.float16),  # K * scale, (16, 224, 32)
        "vt": vt.astype(np.float16),  # V^T, (16, 32, 224)
        "mask": mask,
    }


def tg_block_t(xt, w):
    """one decoder block, feature-major: xt = x^T, (512, Q) half. The queries are the vector lanes -- the HVX-natural
    layout for independent queries: every reduction (LayerNorm over features, softmax over seen tokens, the self score over
    head_dim) runs along the outer axis with contiguous 32-query vector loads, and every matmul is weights x activations
    (qkv^T = Wqkv . x^T, S^T = K_h . q_h^T, o_h^T = V_h^T . P^T, ...), the weights being HMX's A operand as stored."""
    from tinygrad import Tensor, dtypes

    T = lambda a: Tensor(a)  # noqa: E731
    q_n = xt.shape[1]

    def ln(t, gb):
        f = t.float()
        mu = f.mean(0, keepdim=True)
        c = f - mu
        return (c * ((c * c).mean(0, keepdim=True) + 1e-6).rsqrt() * T(gb[0]).float() + T(gb[1]).float()).cast(dtypes.half).contiguous()

    qkv = T(w["wqkv"]).matmul(ln(xt, w["ln1"]), dtype=dtypes.half) + T(w["bqkv"])  # (1536, Q)
    q, k, v = (qkv[i * D : (i + 1) * D].reshape(HEADS, HD, q_n) for i in range(3))  # (16, 32, Q)
    s = T(w["km"]).matmul(q.contiguous(), dtype=dtypes.half).contiguous().float() + T(w["mask"])  # S^T, (16, 224, Q)
    ss = (q.float() * k.float()).sum(1, keepdim=True) * (HD**-0.5)  # (16, 1, Q)
    m = s.max(1, keepdim=True).maximum(ss)
    # e = exp(s - m) once, stored half (in (0, 1]); the row sums read it back, and the normalization happens after P V, in
    # its epilogue (o = (V^T e) / sum): fused into both the sum and a separate P = e / sum kernel, the exp ran twice
    # the exponent in half (s - m <= 0, e in (0, 1]): the DSP backend's hf exp2 then runs 64 lanes per register (as the hand
    # kernel), not 32 through float
    e, es = (s - m).cast(dtypes.half).exp().contiguous(), (ss - m).exp()
    inv = (1.0 / (e.float().sum(1, keepdim=True) + es)).contiguous()
    # the self term's weight is materialized (16 x Q): fused into P V's epilogue it was a scalar exp per output element
    ps = (es * inv).contiguous()
    o = T(w["vt"]).matmul(e, dtype=dtypes.half).float() * inv + ps * v.float()  # (16, 32, Q)
    # materialized as (16, 32, Q) and only then viewed as (512, Q): a (512, Q) kernel output merges head and d into one
    # axis, P's index then depends on it (row // 32) and P V isn't a matmul the tensor core takes (13 ms on HVX, 5.8 on HMX)
    o = o.cast(dtypes.half).contiguous().reshape(D, q_n)
    xt = xt + T(w["wproj"]).matmul(o, dtype=dtypes.half) + T(w["bproj"])
    h = (T(w["w1"]).matmul(ln(xt, w["ln2"]), dtype=dtypes.half) + T(w["b1"])).contiguous()
    g = h.gelu(approximate="tanh").contiguous()  # in half, as the hand kernel (hf exp2 on the DSP)
    return xt + T(w["w2"]).matmul(g, dtype=dtypes.half) + T(w["b2"])


def cmd_check(a):
    import capture
    import ref as R
    import torch
    from tinygrad import Tensor

    torch.set_grad_enabled(False)
    import model as M

    m = M.load_mcc(str(R.CKPT))
    kv = np.load(R.WORK / "kv_quest2m.npz")
    d = Path(a.data)
    x0 = np.fromfile(d / "x0.bin", np.float16).reshape(-1, D)[: a.q]
    tr = a.layout == "t"
    x = Tensor(np.ascontiguousarray(x0.T) if tr else x0).realize()
    blk, wts = (tg_block_t, block_weights_t) if tr else (tg_block, block_weights)
    capture.start(run=not a.no_run)
    for b in range(a.blocks):
        x = blk(x, wts(m.decoder_blocks[b], kv["k"][b], kv["v"][b]))
    x = x.realize()
    calls = capture.stop()
    if a.no_run:
        capture.save(calls, Path(a.save), out_addr=capture.addr_of(x))
        print(f"recorded {len(calls)} kernel calls ({sum('__hmx_' in c.src for c in calls)} HMX) -> {a.save}")
        return
    got = x.numpy().astype(np.float64)
    if tr:
        got = got.T
    ref = np.fromfile(d / f"ref_out{a.blocks - 1}.bin", np.float32).reshape(-1, D)[: a.q].astype(np.float64)
    cs = float((got * ref).sum() / np.sqrt((got**2).sum() * (ref**2).sum()))
    print(
        f"tinygrad, {a.blocks} block(s), Q={a.q}: {len(calls)} kernel calls ({sum('__hmx_' in c.src for c in calls)} HMX); "
        f"vs float64 max abs err {np.abs(got - ref).max():.4g} (max |ref| {np.abs(ref).max():.4g}), cos {cs:.7f}"
    )
    if a.save:
        capture.save(calls, Path(a.save), out_addr=capture.addr_of(x))
        print(f"saved the kernel calls to {a.save}")


def main():
    ap = argparse.ArgumentParser()
    sub = ap.add_subparsers(dest="cmd", required=True)
    c = sub.add_parser("check")
    c.add_argument("--data", required=True)
    c.add_argument("--q", type=int, default=64)
    c.add_argument("--blocks", type=int, default=1)
    c.add_argument("--save")
    c.add_argument("--no-run", action="store_true")
    c.add_argument("--layout", default="t", choices=["t", "rows"], help="t: feature-major (x^T; default), rows: x as (Q, 512)")
    a = ap.parse_args()
    {"check": cmd_check}[a.cmd](a)


if __name__ == "__main__":
    main()
