/* DSP side of the fpn_rpc FastRPC skel (TVM-free, same pattern as ../roialign_fast/):
 *   transpose -- layout_kernels.h's NCHW->NHWC fp32 transpose (mode 0 scalar, 1 HVX pixel-block-outer,
 *                2 = 1 + l2fetch, 3 HVX channel-group-outer),
 *                split over QuRT threads by pixel range -- the cost of converting today's NCHW
 *                backbone outputs for the channels-last RoiAlign kernel.
 *   conv_out  -- the four real FPN output convs with the fused requantize+dequantize epilogue,
 *                writing fp32 either channels-last or NCHW (tinygrad-generated by
 *                ../hex_conv3x3_fpnout_kernel.py into fpn_out_kernels.c).
 *   roialign  -- ../roialign_fast/roialign_kernel.h's prefetching kernel, split over threads by RoI.
 * Every call is timed on the DSP with HAP_perf_get_time_us. */
#include <stdlib.h>
#include "fpn_rpc.h"
#include "qurt.h"
#include "HAP_power.h"
#include "layout_kernels.h"
#include "roialign_kernel.h"
#include "fpn_out_kernels.c"

extern unsigned long long HAP_perf_get_time_us(void);

/* turbo=1: DCVS off, core AND bus (DDR) clock pinned to the TURBO corner (a memory-bound transpose
 * depends on the bus vote, unlike ../roialign_fast's latency-bound kernel); turbo=0: back to DCVS. */
AEEResult fpn_rpc_perf_vote(remote_handle64 h, int32 turbo, int32* rc) {
  void* ctx = (void*)(uintptr_t)h;
  HAP_power_request_t req = {0};
  req.type = HAP_power_set_HVX;
  req.hvx.power_up = 1;
  int r = HAP_power_set(ctx, &req);
  if (turbo) {
    r = r ? r : HAP_power_set_dcvs_option(ctx, FALSE, HAP_DCVS_V2_PERFORMANCE_MODE);
    r = r ? r : HAP_power_set_core_corner(ctx, HAP_DCVS_VCORNER_TURBO, HAP_DCVS_VCORNER_TURBO, HAP_DCVS_VCORNER_TURBO);
    r = r ? r : HAP_power_set_bus_corner(ctx, HAP_DCVS_VCORNER_TURBO, HAP_DCVS_VCORNER_TURBO, HAP_DCVS_VCORNER_TURBO);
  } else {
    r = r ? r : HAP_power_set_dcvs_option(ctx, TRUE, HAP_DCVS_V2_PERFORMANCE_MODE);
  }
  *rc = r;
  return 0;
}

int fpn_rpc_open(const char* uri, remote_handle64* h) {
  *h = (remote_handle64)(uintptr_t)malloc(1);
  return *h ? 0 : -1;
}
int fpn_rpc_close(remote_handle64 h) {
  if (h) free((void*)(uintptr_t)h);
  return 0;
}

#define MAX_THREADS 8
#define STACK_SIZE 16384
static char stacks[MAX_THREADS][STACK_SIZE] __attribute__((aligned(128)));

typedef struct { void (*fn)(void*); void* arg; } task_t;
static void thread_main(void* p) {
  task_t* t = (task_t*)p;
  int locked = qurt_hvx_lock(QURT_HVX_MODE_128B) == 0;
  t->fn(t->arg);
  if (locked) qurt_hvx_unlock();
  qurt_thread_exit(0);
}
/* Run fn(args[i]) for i < n on n QuRT threads (n == 1: on the calling thread, HVX locked). */
static int run_threads(void (*fn)(void*), void** args, int n) {
  if (n == 1) {
    int locked = qurt_hvx_lock(QURT_HVX_MODE_128B) == 0;
    fn(args[0]);
    if (locked) qurt_hvx_unlock();
    return 0;
  }
  task_t tasks[MAX_THREADS];
  qurt_thread_t tids[MAX_THREADS];
  for (int i = 0; i < n; i++) {
    tasks[i] = (task_t){fn, args[i]};
    qurt_thread_attr_t attr;
    qurt_thread_attr_init(&attr);
    qurt_thread_attr_set_stack_addr(&attr, stacks[i]);
    qurt_thread_attr_set_stack_size(&attr, STACK_SIZE);
    qurt_thread_attr_set_priority(&attr, qurt_thread_get_priority(qurt_thread_get_id()));
    if (qurt_thread_create(&tids[i], &attr, thread_main, &tasks[i]) != QURT_EOK) return -2;
  }
  for (int i = 0; i < n; i++) { int st; qurt_thread_join(tids[i], &st); }
  return 0;
}

typedef struct { const float* in; float* out; int C, HW, p0, p1, mode; } tjob_t;
static void tjob(void* p) {
  tjob_t* j = (tjob_t*)p;
  if (j->mode == 0) transpose_chw_hwc_scalar(j->in, j->out, j->C, j->HW, j->p0, j->p1);
  else if (j->mode == 3) transpose_chw_hwc_hvx_cout(j->in, j->out, j->C, j->HW, j->p0, j->p1);
  else transpose_chw_hwc_hvx(j->in, j->out, j->C, j->HW, j->p0, j->p1, j->mode == 2);
}

/* chwLen must include >= 32 floats of slack past C*HW (the HVX kernel's tail over-read). */
AEEResult fpn_rpc_transpose(remote_handle64 h, const float* chw, int chwLen, int32 C, int32 HW, int32 nthreads,
                            int32 mode, float* hwc, int hwcLen, uint64* dsp_us) {
  if (C % 32 || chwLen < C * HW + 32 || hwcLen < C * HW) return -1;
  if (nthreads < 1) nthreads = 1;
  if (nthreads > MAX_THREADS) nthreads = MAX_THREADS;
  tjob_t jobs[MAX_THREADS];
  void* args[MAX_THREADS];
  int blocks = (HW + 31) / 32, per = (blocks + nthreads - 1) / nthreads, n = 0;
  for (int t = 0; t < nthreads; t++) {
    int p0 = t * per * 32, p1 = (t + 1) * per * 32;
    if (p1 > HW) p1 = HW;
    if (p0 >= p1) break;
    jobs[n] = (tjob_t){chw, hwc, C, HW, p0, p1, mode};
    args[n] = &jobs[n];
    n++;
  }
  unsigned long long t0 = HAP_perf_get_time_us();
  int rc = run_threads(tjob, args, n);
  *dsp_us = HAP_perf_get_time_us() - t0;
  return rc;
}

typedef void (*conv_fn)(float*, unsigned char*, unsigned char*, int*);
static const conv_fn convs[4][2] = {
  {fpnout_P5_hwc, fpnout_P5_chw}, {fpnout_P4_hwc, fpnout_P4_chw},
  {fpnout_P3_hwc, fpnout_P3_chw}, {fpnout_P2_hwc, fpnout_P2_chw},
};
static const int dims[4][2] = {{25, 34}, {50, 68}, {100, 136}, {200, 272}};

typedef struct { conv_fn f; float* o; unsigned char* a; unsigned char* w; int* b; } cjob_t;
static void cjob(void* p) { cjob_t* j = (cjob_t*)p; j->f(j->o, j->a, j->w, j->b); }

/* level 0..3 = P5, P4, P3, P2; layout 0 = channels-last, 1 = NCHW. Single-threaded. */
AEEResult fpn_rpc_conv_out(remote_handle64 h, int32 level, int32 layout, const unsigned char* apad, int apadLen,
                           const unsigned char* wp, int wpLen, const int32* bias, int biasLen, float* out,
                           int outLen, uint64* dsp_us) {
  if (level < 0 || level > 3 || layout < 0 || layout > 1) return -1;
  int ih = dims[level][0], iw = dims[level][1];
  if (apadLen < (ih + 2) * (iw + 2) * 256 || wpLen < 9 * 256 * 256 || biasLen < 256 || outLen < ih * iw * 256) return -1;
  cjob_t j = {convs[level][layout], out, (unsigned char*)apad, (unsigned char*)wp, (int*)bias};
  void* args[1] = {&j};
  unsigned long long t0 = HAP_perf_get_time_us();
  int rc = run_threads(cjob, args, 1);
  *dsp_us = HAP_perf_get_time_us() - t0;
  return rc;
}

typedef struct { const float* feat; const float* rois; float* out; int H, W, C, R, OH, OW, sr; float scale; } rjob_t;
static void rjob(void* p) {
  rjob_t* j = (rjob_t*)p;
  roialign_hwc_pf(j->feat, j->H, j->W, j->C, j->rois, j->R, j->OH, j->OW, j->sr, j->scale, j->out);
}

AEEResult fpn_rpc_roialign(remote_handle64 h, const float* feat, int featLen, const float* rois, int roisLen,
                           int32 H, int32 W, int32 C, int32 OH, int32 OW, int32 sr, float scale, int32 nthreads,
                           float* out, int outLen, uint64* dsp_us) {
  int R = roisLen / 4;
  if (C % 32 || C > 32 * ROI_MAX_NV || featLen < H * W * C || outLen < R * OH * OW * C) return -1;
  if (nthreads < 1) nthreads = 1;
  if (nthreads > MAX_THREADS) nthreads = MAX_THREADS;
  if (nthreads > R) nthreads = R > 0 ? R : 1;
  rjob_t jobs[MAX_THREADS];
  void* args[MAX_THREADS];
  int per = (R + nthreads - 1) / nthreads, n = 0;
  for (int t = 0; t < nthreads; t++) {
    int r0 = t * per, r1 = r0 + per > R ? R : r0 + per;
    if (r0 >= r1) break;
    jobs[n] = (rjob_t){feat, rois + 4 * r0, out + (long)r0 * OH * OW * C, H, W, C, r1 - r0, OH, OW, sr, scale};
    args[n] = &jobs[n];
    n++;
  }
  unsigned long long t0 = HAP_perf_get_time_us();
  int rc = run_threads(rjob, args, n);
  *dsp_us = HAP_perf_get_time_us() - t0;
  return rc;
}
