#version 450
#define INFINITY uintBitsToFloat(0x7f800000u)
#define NAN uintBitsToFloat(0x7fc00000u)
// kernel: r_98_4_8_16_4_4_16_4
layout(local_size_x=8, local_size_y=16, local_size_z=1) in;
layout(std430, set=0, binding=0) buffer B0 { float data0_802816[]; };
layout(std430, set=0, binding=1) buffer B1 { float data1_200704[]; };
layout(std430, set=0, binding=2) buffer B2 { float data2_16384[]; };
void main() {
  float buf0[16];
  int gidx0 = int(gl_WorkGroupID.x); /* 4 */
  int gidx1 = int(gl_WorkGroupID.y); /* 98 */
  int lidx0 = int(gl_LocalInvocationID.x); /* 8 */
  int lidx1 = int(gl_LocalInvocationID.y); /* 16 */
  int alu0 = ((gidx0<<6)+(lidx1<<2));
  buf0[0] = 0.0f;
  buf0[1] = 0.0f;
  buf0[2] = 0.0f;
  buf0[3] = 0.0f;
  buf0[4] = 0.0f;
  buf0[5] = 0.0f;
  buf0[6] = 0.0f;
  buf0[7] = 0.0f;
  buf0[8] = 0.0f;
  buf0[9] = 0.0f;
  buf0[10] = 0.0f;
  buf0[11] = 0.0f;
  buf0[12] = 0.0f;
  buf0[13] = 0.0f;
  buf0[14] = 0.0f;
  buf0[15] = 0.0f;
  for (int Ridx0 = 0; Ridx0 < 16; Ridx0++) {
    int alu17 = ((gidx1<<11)+(lidx0<<8)+(Ridx0<<2));
    float val0 = data1_200704[(alu17+1)];
    float val1 = data1_200704[(alu17+2)];
    float val2 = data1_200704[(alu17+3)];
    float val3 = data1_200704[(alu17+64)];
    float val4 = data1_200704[(alu17+65)];
    float val5 = data1_200704[(alu17+66)];
    float val6 = data1_200704[(alu17+67)];
    float val7 = data1_200704[(alu17+128)];
    float val8 = data1_200704[(alu17+129)];
    float val9 = data1_200704[(alu17+130)];
    float val10 = data1_200704[(alu17+131)];
    float val11 = data1_200704[(alu17+192)];
    float val12 = data1_200704[(alu17+193)];
    float val13 = data1_200704[(alu17+194)];
    float val14 = data1_200704[(alu17+195)];
    float val15 = data1_200704[alu17];
    int alu18 = (alu0+(Ridx0<<10));
    float val16 = data2_16384[(alu18+1)];
    float val17 = data2_16384[(alu18+2)];
    float val18 = data2_16384[(alu18+3)];
    float val19 = data2_16384[(alu18+256)];
    float val20 = data2_16384[(alu18+257)];
    float val21 = data2_16384[(alu18+258)];
    float val22 = data2_16384[(alu18+259)];
    float val23 = data2_16384[(alu18+512)];
    float val24 = data2_16384[(alu18+513)];
    float val25 = data2_16384[(alu18+514)];
    float val26 = data2_16384[(alu18+515)];
    float val27 = data2_16384[(alu18+768)];
    float val28 = data2_16384[(alu18+769)];
    float val29 = data2_16384[(alu18+770)];
    float val30 = data2_16384[(alu18+771)];
    float val31 = data2_16384[alu18];
    buf0[0] = (buf0[0]+((val15*val31)+(val0*val19)+(val1*val23)+(val2*val27)));
    buf0[1] = (buf0[1]+((val15*val16)+(val0*val20)+(val1*val24)+(val2*val28)));
    buf0[2] = (buf0[2]+((val15*val17)+(val0*val21)+(val1*val25)+(val2*val29)));
    buf0[3] = (buf0[3]+((val15*val18)+(val0*val22)+(val1*val26)+(val2*val30)));
    buf0[4] = (buf0[4]+((val3*val31)+(val4*val19)+(val5*val23)+(val6*val27)));
    buf0[5] = (buf0[5]+((val3*val16)+(val4*val20)+(val5*val24)+(val6*val28)));
    buf0[6] = (buf0[6]+((val3*val17)+(val4*val21)+(val5*val25)+(val6*val29)));
    buf0[7] = (buf0[7]+((val3*val18)+(val4*val22)+(val5*val26)+(val6*val30)));
    buf0[8] = (buf0[8]+((val7*val31)+(val8*val19)+(val9*val23)+(val10*val27)));
    buf0[9] = (buf0[9]+((val7*val16)+(val8*val20)+(val9*val24)+(val10*val28)));
    buf0[10] = (buf0[10]+((val7*val17)+(val8*val21)+(val9*val25)+(val10*val29)));
    buf0[11] = (buf0[11]+((val7*val18)+(val8*val22)+(val9*val26)+(val10*val30)));
    buf0[12] = (buf0[12]+((val11*val31)+(val12*val19)+(val13*val23)+(val14*val27)));
    buf0[13] = (buf0[13]+((val11*val16)+(val12*val20)+(val13*val24)+(val14*val28)));
    buf0[14] = (buf0[14]+((val11*val17)+(val12*val21)+(val13*val25)+(val14*val29)));
    buf0[15] = (buf0[15]+((val11*val18)+(val12*val22)+(val13*val26)+(val14*val30)));
  }
  int alu36 = (alu0+(gidx1<<13)+(lidx0<<10));
  data0_802816[(alu36+1)] = buf0[1];
  data0_802816[(alu36+2)] = buf0[2];
  data0_802816[(alu36+3)] = buf0[3];
  data0_802816[(alu36+256)] = buf0[4];
  data0_802816[(alu36+257)] = buf0[5];
  data0_802816[(alu36+258)] = buf0[6];
  data0_802816[(alu36+259)] = buf0[7];
  data0_802816[(alu36+512)] = buf0[8];
  data0_802816[(alu36+513)] = buf0[9];
  data0_802816[(alu36+514)] = buf0[10];
  data0_802816[(alu36+515)] = buf0[11];
  data0_802816[(alu36+768)] = buf0[12];
  data0_802816[(alu36+769)] = buf0[13];
  data0_802816[(alu36+770)] = buf0[14];
  data0_802816[(alu36+771)] = buf0[15];
  data0_802816[alu36] = buf0[0];
}
