#version 450
#define INFINITY uintBitsToFloat(0x7f800000u)
#define NAN uintBitsToFloat(0x7fc00000u)
// kernel: r_4_49_16_8_4_4_72_4
layout(local_size_x=16, local_size_y=8, local_size_z=1) in;
layout(std430, set=0, binding=0) buffer B0 { float data0_50176[]; };
layout(std430, set=0, binding=1) buffer B1 { float data1_451584[]; };
layout(std430, set=0, binding=2) buffer B2 { float data2_589824[]; };
shared float buf2[2048];
void main() {
  float buf0[16];
  float buf1[16];
  int gidx0 = int(gl_WorkGroupID.x); /* 49 */
  int gidx1 = int(gl_WorkGroupID.y); /* 4 */
  int lidx0 = int(gl_LocalInvocationID.x); /* 16 */
  int lidx1 = int(gl_LocalInvocationID.y); /* 8 */
  int alu0 = ((gidx1<<6)+(lidx0<<2));
  buf0[0] = 0.0f;
  buf0[1] = 0.0f;
  buf0[2] = 0.0f;
  buf0[3] = 0.0f;
  buf0[4] = 0.0f;
  buf0[5] = 0.0f;
  buf0[6] = 0.0f;
  buf0[7] = 0.0f;
  buf0[8] = 0.0f;
  buf0[9] = 0.0f;
  buf0[10] = 0.0f;
  buf0[11] = 0.0f;
  buf0[12] = 0.0f;
  buf0[13] = 0.0f;
  buf0[14] = 0.0f;
  buf0[15] = 0.0f;
  for (int Ridx0 = 0; Ridx0 < 72; Ridx0++) {
    int alu17 = ((lidx1<<2)+(Ridx0<<5)+(gidx0*9216));
    float val0 = data1_451584[(alu17+1)];
    float val1 = data1_451584[(alu17+2)];
    float val2 = data1_451584[(alu17+3)];
    float val3 = data1_451584[(alu17+2304)];
    float val4 = data1_451584[(alu17+2305)];
    float val5 = data1_451584[(alu17+2306)];
    float val6 = data1_451584[(alu17+2307)];
    float val7 = data1_451584[(alu17+4608)];
    float val8 = data1_451584[(alu17+4609)];
    float val9 = data1_451584[(alu17+4610)];
    float val10 = data1_451584[(alu17+4611)];
    float val11 = data1_451584[(alu17+6912)];
    float val12 = data1_451584[(alu17+6913)];
    float val13 = data1_451584[(alu17+6914)];
    float val14 = data1_451584[(alu17+6915)];
    float val15 = data1_451584[alu17];
    int alu18 = (alu0+(lidx1<<10)+(Ridx0<<13));
    float val16 = data2_589824[(alu18+1)];
    float val17 = data2_589824[(alu18+2)];
    float val18 = data2_589824[(alu18+3)];
    float val19 = data2_589824[(alu18+256)];
    float val20 = data2_589824[(alu18+257)];
    float val21 = data2_589824[(alu18+258)];
    float val22 = data2_589824[(alu18+259)];
    float val23 = data2_589824[(alu18+512)];
    float val24 = data2_589824[(alu18+513)];
    float val25 = data2_589824[(alu18+514)];
    float val26 = data2_589824[(alu18+515)];
    float val27 = data2_589824[(alu18+768)];
    float val28 = data2_589824[(alu18+769)];
    float val29 = data2_589824[(alu18+770)];
    float val30 = data2_589824[(alu18+771)];
    float val31 = data2_589824[alu18];
    buf0[0] = (buf0[0]+((val15*val31)+(val0*val19)+(val1*val23)+(val2*val27)));
    buf0[1] = (buf0[1]+((val3*val31)+(val4*val19)+(val5*val23)+(val6*val27)));
    buf0[2] = (buf0[2]+((val7*val31)+(val8*val19)+(val9*val23)+(val10*val27)));
    buf0[3] = (buf0[3]+((val11*val31)+(val12*val19)+(val13*val23)+(val14*val27)));
    buf0[4] = (buf0[4]+((val15*val16)+(val0*val20)+(val1*val24)+(val2*val28)));
    buf0[5] = (buf0[5]+((val3*val16)+(val4*val20)+(val5*val24)+(val6*val28)));
    buf0[6] = (buf0[6]+((val7*val16)+(val8*val20)+(val9*val24)+(val10*val28)));
    buf0[7] = (buf0[7]+((val11*val16)+(val12*val20)+(val13*val24)+(val14*val28)));
    buf0[8] = (buf0[8]+((val15*val17)+(val0*val21)+(val1*val25)+(val2*val29)));
    buf0[9] = (buf0[9]+((val3*val17)+(val4*val21)+(val5*val25)+(val6*val29)));
    buf0[10] = (buf0[10]+((val7*val17)+(val8*val21)+(val9*val25)+(val10*val29)));
    buf0[11] = (buf0[11]+((val11*val17)+(val12*val21)+(val13*val25)+(val14*val29)));
    buf0[12] = (buf0[12]+((val15*val18)+(val0*val22)+(val1*val26)+(val2*val30)));
    buf0[13] = (buf0[13]+((val3*val18)+(val4*val22)+(val5*val26)+(val6*val30)));
    buf0[14] = (buf0[14]+((val7*val18)+(val8*val22)+(val9*val26)+(val10*val30)));
    buf0[15] = (buf0[15]+((val11*val18)+(val12*val22)+(val13*val26)+(val14*val30)));
  }
  int alu36 = (lidx0<<7);
  int alu37 = (alu36+(lidx1<<4));
  buf2[(alu37+1)] = buf0[1];
  buf2[(alu37+2)] = buf0[2];
  buf2[(alu37+3)] = buf0[3];
  buf2[(alu37+4)] = buf0[4];
  buf2[(alu37+5)] = buf0[5];
  buf2[(alu37+6)] = buf0[6];
  buf2[(alu37+7)] = buf0[7];
  buf2[(alu37+8)] = buf0[8];
  buf2[(alu37+9)] = buf0[9];
  buf2[(alu37+10)] = buf0[10];
  buf2[(alu37+11)] = buf0[11];
  buf2[(alu37+12)] = buf0[12];
  buf2[(alu37+13)] = buf0[13];
  buf2[(alu37+14)] = buf0[14];
  buf2[(alu37+15)] = buf0[15];
  buf2[alu37] = buf0[0];
  memoryBarrierShared(); barrier();
  buf1[0] = 0.0f;
  buf1[1] = 0.0f;
  buf1[2] = 0.0f;
  buf1[3] = 0.0f;
  buf1[4] = 0.0f;
  buf1[5] = 0.0f;
  buf1[6] = 0.0f;
  buf1[7] = 0.0f;
  buf1[8] = 0.0f;
  buf1[9] = 0.0f;
  buf1[10] = 0.0f;
  buf1[11] = 0.0f;
  buf1[12] = 0.0f;
  buf1[13] = 0.0f;
  buf1[14] = 0.0f;
  buf1[15] = 0.0f;
  for (int Ridx107 = 0; Ridx107 < 8; Ridx107++) {
    int alu71 = (alu36+(Ridx107<<4));
    float val32 = buf2[(alu71+1)];
    float val33 = buf2[(alu71+2)];
    float val34 = buf2[(alu71+3)];
    float val35 = buf2[(alu71+4)];
    float val36 = buf2[(alu71+5)];
    float val37 = buf2[(alu71+6)];
    float val38 = buf2[(alu71+7)];
    float val39 = buf2[(alu71+8)];
    float val40 = buf2[(alu71+9)];
    float val41 = buf2[(alu71+10)];
    float val42 = buf2[(alu71+11)];
    float val43 = buf2[(alu71+12)];
    float val44 = buf2[(alu71+13)];
    float val45 = buf2[(alu71+14)];
    float val46 = buf2[(alu71+15)];
    float val47 = buf2[alu71];
    buf1[0] = (buf1[0]+val47);
    buf1[1] = (buf1[1]+val32);
    buf1[2] = (buf1[2]+val33);
    buf1[3] = (buf1[3]+val34);
    buf1[4] = (buf1[4]+val35);
    buf1[5] = (buf1[5]+val36);
    buf1[6] = (buf1[6]+val37);
    buf1[7] = (buf1[7]+val38);
    buf1[8] = (buf1[8]+val39);
    buf1[9] = (buf1[9]+val40);
    buf1[10] = (buf1[10]+val41);
    buf1[11] = (buf1[11]+val42);
    buf1[12] = (buf1[12]+val43);
    buf1[13] = (buf1[13]+val44);
    buf1[14] = (buf1[14]+val45);
    buf1[15] = (buf1[15]+val46);
  }
  int alu89 = (alu0+(gidx0<<10));
  bool alu90 = (lidx1==0);
  if (alu90) {
    data0_50176[(alu89+1)] = buf1[4];
  }
  if (alu90) {
    data0_50176[(alu89+2)] = buf1[8];
  }
  if (alu90) {
    data0_50176[(alu89+3)] = buf1[12];
  }
  if (alu90) {
    data0_50176[(alu89+256)] = buf1[1];
  }
  if (alu90) {
    data0_50176[(alu89+257)] = buf1[5];
  }
  if (alu90) {
    data0_50176[(alu89+258)] = buf1[9];
  }
  if (alu90) {
    data0_50176[(alu89+259)] = buf1[13];
  }
  if (alu90) {
    data0_50176[(alu89+512)] = buf1[2];
  }
  if (alu90) {
    data0_50176[(alu89+513)] = buf1[6];
  }
  if (alu90) {
    data0_50176[(alu89+514)] = buf1[10];
  }
  if (alu90) {
    data0_50176[(alu89+515)] = buf1[14];
  }
  if (alu90) {
    data0_50176[(alu89+768)] = buf1[3];
  }
  if (alu90) {
    data0_50176[(alu89+769)] = buf1[7];
  }
  if (alu90) {
    data0_50176[(alu89+770)] = buf1[11];
  }
  if (alu90) {
    data0_50176[(alu89+771)] = buf1[15];
  }
  if (alu90) {
    data0_50176[alu89] = buf1[0];
  }
}
